export { default as HomePage } from './HomePage'
export { default as CategoriesPage } from './CategoriesPage'
export { default as SearchPage } from './SearchPage'
export { default as FavoritesPage } from './FavoritesPage'
export { default as PerformanceDiagnosticsPage } from './PerformanceDiagnosticsPage'
